
#======================================#
#========== Project settings ==========#
#======================================#

#是否演示模式
demoMode: false

#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8888
  servlet:
    context-path: /myBatisTool
  tomcat:
    uri-encoding: UTF-8
    
#======================================#

#======================================#
#========== MQ sttings ==========#
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.200.56:1521:orcl
    username: DB_CRC_CODE
    password: DB_CRC_CODE
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.200.58:61616
#    broker-url: tcp://10.217.247.159:61616
    in-memory: false
    pool:
      max-connections: 5
      idle-timeout: 30s
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  ##xml文件的路径配置
  mapper-locations:  classpath*:mybatis/mqsync/**.xml